{
  description = "Nix flake for time-rs submodule";

  inputs = {
    nixpkgs.url = "github:meta-introspector/nixpkgs?ref=feature/CRQ-016-nixify";
    cargo2nix.url = "github:meta-introspector/cargo2nix?ref=feature/CRQ-016-nixify"; # Assuming this is the correct cargo2nix flake
    flake-utils.url = "github:meta-introspector/flake-utils?ref=feature/CRQ-016-nixify"; # Add flake-utils input
  };

  outputs = { self, nixpkgs, cargo2nix, flake-utils }: 
    let
      systems = [ "aarch64-linux" ];
      timeRsOverlay = import ./overlay.nix; # Import the new overlay
    in
    flake-utils.lib.eachDefaultSystem systems (system:
      let
        pkgs = import nixpkgs {
          inherit system;
          overlays = [ cargo2nix.overlays.default timeRsOverlay ]; # Apply the new overlay
        };
        # Generate the Rust package set using cargo2nix
        rustPkgs = pkgs.rustBuilder.makePackageSet {
          packageFun = import ./Cargo.nix; # This file will be generated by cargo2nix
          rustChannel = "stable";
          rustVersion = "1.81.0"; # Use the same stable version as the main project
        };
      in
      {
        packages.time-macros = rustPkgs.workspace.time-macros; # Expose time-macros
        defaultPackage = self.packages.${system}.time-macros;
      }
    );
}